# Generated by Django 4.2.5 on 2023-09-10 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authername', models.CharField(max_length=50)),
                ('date', models.CharField(max_length=50)),
                ('videosnum', models.CharField(max_length=50)),
                ('sub', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='media')),
            ],
        ),
    ]
