# Generated by Django 4.2.5 on 2023-09-10 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_rename_howmany_videos_course_howmany_video'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='howmany_video',
            new_name='howmany_videos',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='image',
            new_name='images',
        ),
    ]
