# Generated by Django 4.2.5 on 2023-09-10 22:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0004_rename_howmany_video_course_howmany_videos_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="course",
            old_name="images",
            new_name="image",
        ),
    ]
