# Generated by Django 4.2.5 on 2023-09-10 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_rename_images_course_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='howmany_videos',
            new_name='howmany_video',
        ),
    ]
