# Generated by Django 4.2.5 on 2023-09-11 04:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0008_web_course_delete_course"),
    ]

    operations = [
        migrations.CreateModel(
            name="contact_form",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("email", models.CharField(max_length=50)),
                ("number", models.IntegerField()),
                ("msg", models.TextField()),
            ],
        ),
    ]
