# Generated by Django 4.2.5 on 2023-10-11 04:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0016_rename_playlist_number_playlist_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="watch_video",
            name="video",
            field=models.FileField(upload_to="media"),
        ),
    ]
