# Generated by Django 4.2.5 on 2023-10-13 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0020_remove_playlist_topic_description_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='playlist',
            new_name='html_playlist',
        ),
    ]
