# Generated by Django 4.2.5 on 2023-10-13 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0021_rename_playlist_html_playlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='css_playlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_thumbnail', models.ImageField(upload_to='media')),
                ('video_title', models.CharField(max_length=50)),
            ],
        ),
    ]
