# Generated by Django 4.2.5 on 2023-10-19 03:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0025_js_course_js_playlist"),
    ]

    operations = [
        migrations.CreateModel(
            name="js_watch_video",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("video", models.FileField(upload_to="media")),
                ("video_thumb", models.ImageField(upload_to="media")),
                ("title", models.CharField(max_length=50)),
                ("date", models.CharField(max_length=50)),
                ("tutor_image", models.ImageField(upload_to="media")),
                ("tutor_name", models.CharField(max_length=50)),
                ("tutor_position", models.CharField(max_length=50)),
                ("description", models.CharField(max_length=100)),
            ],
        ),
    ]
