# Generated by Django 4.2.5 on 2023-10-19 05:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0026_js_watch_video"),
    ]

    operations = [
        migrations.CreateModel(
            name="bootstrap_course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("authername", models.CharField(max_length=50)),
                ("auther_image", models.ImageField(upload_to="media")),
                ("date", models.CharField(max_length=50)),
                ("howmany_video", models.CharField(max_length=50)),
                ("video_title", models.CharField(max_length=50)),
                ("thumbnail", models.ImageField(upload_to="media")),
            ],
        ),
        migrations.CreateModel(
            name="bootstrap_playlist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("video_thumbnail", models.ImageField(upload_to="media")),
                ("video_title", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="bootstrap_watch_video",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("video", models.FileField(upload_to="media")),
                ("video_thumb", models.ImageField(upload_to="media")),
                ("title", models.CharField(max_length=50)),
                ("date", models.CharField(max_length=50)),
                ("tutor_image", models.ImageField(upload_to="media")),
                ("tutor_name", models.CharField(max_length=50)),
                ("tutor_position", models.CharField(max_length=50)),
                ("description", models.CharField(max_length=100)),
            ],
        ),
    ]
