# Generated by Django 4.2.5 on 2023-10-19 06:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0027_bootstrap_course_bootstrap_playlist_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bootstrap_playlist",
            name="video_thumbnail",
            field=models.FileField(upload_to="media"),
        ),
    ]
