# Generated by Django 4.2.5 on 2023-10-19 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0029_alter_watch_video_video_thumb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bootstrap_watch_video',
            name='video_thumb',
            field=models.FileField(upload_to='media'),
        ),
    ]
