# Generated by Django 4.2.5 on 2023-11-03 01:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0041_psql_watch_video"),
    ]

    operations = [
        migrations.CreateModel(
            name="profile_details",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("email", models.EmailField(max_length=254)),
                ("image", models.FileField(blank=True, null=True, upload_to="images")),
            ],
        ),
    ]
