# Generated by Django 4.2.5 on 2023-11-03 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0043_login_form'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login_form',
            name='phone_number',
            field=models.BigIntegerField(),
        ),
    ]
