# Generated by Django 4.2.5 on 2023-11-03 04:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0044_alter_login_form_phone_number"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="login_form",
            new_name="signup_form",
        ),
    ]
