# Generated by Django 4.2.5 on 2023-11-04 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0045_rename_login_form_signup_form'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup_form',
            name='username_name',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
