# Generated by Django 4.2.5 on 2023-11-04 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0048_signup_form_course'),
    ]

    operations = [
        migrations.DeleteModel(
            name='signup_form',
        ),
    ]
