# Generated by Django 4.2.7 on 2023-11-27 07:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0052_rename_python_course_bootstrapcourse_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Playlist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("video_thumbnail", models.ImageField(upload_to="media")),
                ("video_title", models.CharField(max_length=50)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("html", "html"),
                            ("css", "css"),
                            ("js", "js"),
                            ("bootstrap", "bootstrap"),
                            ("react", "react"),
                            ("python", "python"),
                            ("psql", "psql"),
                        ],
                        max_length=50,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Video",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("video", models.FileField(upload_to="media")),
                ("video_thumb", models.FileField(upload_to="media")),
                ("title", models.CharField(max_length=50)),
                ("date", models.CharField(max_length=50)),
                ("tutor_image", models.ImageField(upload_to="media")),
                ("tutor_name", models.CharField(max_length=50)),
                ("tutor_position", models.CharField(max_length=50)),
                ("description", models.CharField(max_length=100)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("html", "html"),
                            ("css", "css"),
                            ("js", "js"),
                            ("bootstrap", "bootstrap"),
                            ("react", "react"),
                            ("python", "python"),
                            ("psql", "psql"),
                        ],
                        max_length=50,
                    ),
                ),
            ],
        ),
        migrations.RenameModel(
            old_name="ContactForm",
            new_name="Contact",
        ),
        migrations.DeleteModel(
            name="BootstrapCourse",
        ),
        migrations.DeleteModel(
            name="BootstrapPlaylist",
        ),
        migrations.DeleteModel(
            name="BootstrapWatchVideo",
        ),
        migrations.DeleteModel(
            name="CssCourse",
        ),
        migrations.DeleteModel(
            name="CssPlaylist",
        ),
        migrations.DeleteModel(
            name="CssWatchVideo",
        ),
        migrations.DeleteModel(
            name="FlutterCourse",
        ),
        migrations.DeleteModel(
            name="HtmlPlaylist",
        ),
        migrations.DeleteModel(
            name="JsCourse",
        ),
        migrations.DeleteModel(
            name="JsPlaylist",
        ),
        migrations.DeleteModel(
            name="JsWatchVideo",
        ),
        migrations.DeleteModel(
            name="PsqlCourse",
        ),
        migrations.DeleteModel(
            name="PsqlPlaylist",
        ),
        migrations.DeleteModel(
            name="PsqlWatchVideo",
        ),
        migrations.DeleteModel(
            name="PythonCourse",
        ),
        migrations.DeleteModel(
            name="PythonPlaylist",
        ),
        migrations.DeleteModel(
            name="PythonWatchVideo",
        ),
        migrations.DeleteModel(
            name="ReactCourse",
        ),
        migrations.DeleteModel(
            name="ReactPlaylist",
        ),
        migrations.DeleteModel(
            name="ReactWatchVideo",
        ),
        migrations.DeleteModel(
            name="SelectboxCourse",
        ),
        migrations.DeleteModel(
            name="WatchVideo",
        ),
        migrations.RenameField(
            model_name="contact",
            old_name="msg",
            new_name="message",
        ),
        migrations.RemoveField(
            model_name="teacherprofile",
            name="wp_url",
        ),
        migrations.AddField(
            model_name="playlisthead",
            name="category",
            field=models.CharField(
                choices=[
                    ("html", "html"),
                    ("css", "css"),
                    ("js", "js"),
                    ("bootstrap", "bootstrap"),
                    ("react", "react"),
                    ("python", "python"),
                    ("psql", "psql"),
                ],
                default=1,
                max_length=50,
            ),
            preserve_default=False,
        ),
        migrations.RenameModel(
            old_name="HtmlCourse",
            new_name="Course",
        ),
        migrations.AddField(
            model_name="video",
            name="Course",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="web.course"
            ),
        ),
        migrations.AddField(
            model_name="playlist",
            name="Course",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="web.course"
            ),
        ),
        migrations.AddField(
            model_name="playlisthead",
            name="Playlist",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="web.playlist",
            ),
            preserve_default=False,
        ),
    ]
