# Generated by Django 4.2.7 on 2023-11-28 06:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0053_playlist_video_rename_contactform_contact_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="teacherprofile",
            name="insta_url",
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name="teacherprofile",
            name="linkedin_url",
            field=models.URLField(),
        ),
    ]
