# Generated by Django 4.2.7 on 2023-11-28 06:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0054_alter_teacherprofile_insta_url_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="teacherprofile",
            name="insta_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
