# Generated by Django 4.2.7 on 2023-11-28 06:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0055_alter_teacherprofile_insta_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profiledetails",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="images"),
        ),
    ]
