# Generated by Django 4.2.7 on 2023-11-28 07:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0056_alter_profiledetails_image"),
    ]

    operations = [
        migrations.RenameField(
            model_name="playlist",
            old_name="Course",
            new_name="course",
        ),
    ]
