# Generated by Django 4.2.7 on 2023-11-28 07:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0057_rename_course_playlist_course"),
    ]

    operations = [
        migrations.AlterField(
            model_name="playlisthead",
            name="Playlist",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="web.course"
            ),
        ),
    ]
