# Generated by Django 4.2.7 on 2023-11-28 07:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0058_alter_playlisthead_playlist"),
    ]

    operations = [
        migrations.AddField(
            model_name="playlist",
            name="date",
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="playlist",
            name="how_many_videos",
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="playlist",
            name="topic_description",
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="playlist",
            name="topic_thumb",
            field=models.ImageField(default=1, upload_to="media"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="playlist",
            name="topic_title",
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="playlist",
            name="tutor_image",
            field=models.ImageField(default=1, upload_to="media"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="playlist",
            name="tutor_name",
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name="PlaylistHead",
        ),
    ]
