# Generated by Django 4.2.7 on 2023-11-28 08:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0059_playlist_date_playlist_how_many_videos_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="video",
            name="video",
            field=models.URLField(),
        ),
    ]
