# Generated by Django 4.2.7 on 2023-11-28 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0061_remove_playlist_topic_thumb_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="playlist",
            old_name="course",
            new_name="Course",
        ),
        migrations.RemoveField(
            model_name="playlist",
            name="date",
        ),
        migrations.RemoveField(
            model_name="playlist",
            name="how_many_videos",
        ),
        migrations.RemoveField(
            model_name="playlist",
            name="topic_description",
        ),
        migrations.RemoveField(
            model_name="playlist",
            name="tutor_image",
        ),
        migrations.RemoveField(
            model_name="playlist",
            name="tutor_name",
        ),
        migrations.CreateModel(
            name="PlaylistHead",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("topic_thumb", models.ImageField(upload_to="media")),
                ("how_many_videos", models.CharField(max_length=50)),
                ("tutor_image", models.ImageField(upload_to="media")),
                ("tutor_name", models.CharField(max_length=50)),
                ("date", models.CharField(max_length=50)),
                ("topic_title", models.CharField(max_length=100)),
                ("topic_description", models.CharField(max_length=100)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("html", "html"),
                            ("css", "css"),
                            ("js", "js"),
                            ("bootstrap", "bootstrap"),
                            ("react", "react"),
                            ("python", "python"),
                            ("psql", "psql"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "Playlist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="web.playlist"
                    ),
                ),
            ],
        ),
    ]
