# Generated by Django 4.2.7 on 2023-11-28 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0062_rename_course_playlist_course_remove_playlist_date_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="playlisthead",
            name="Playlist",
        ),
        migrations.AddField(
            model_name="playlisthead",
            name="Course",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, to="web.course"
            ),
            preserve_default=False,
        ),
    ]
