# Generated by Django 4.2.7 on 2023-11-28 09:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0064_rename_course_playlist_course_playlist_topic_thumb"),
    ]

    operations = [
        migrations.RenameField(
            model_name="playlisthead",
            old_name="Course",
            new_name="course",
        ),
        migrations.RemoveField(
            model_name="playlist",
            name="topic_thumb",
        ),
    ]
