# Generated by Django 4.2.7 on 2023-11-28 11:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0067_remove_video_video_thumb"),
    ]

    operations = [
        migrations.CreateModel(
            name="Topic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("html", "HTML"),
                            ("css", "CSS"),
                            ("js", "JavaScript"),
                            ("bootstrap", "Bootstrap"),
                            ("react", "React"),
                            ("python", "Python"),
                            ("psql", "PostgreSQL"),
                        ],
                        max_length=50,
                    ),
                ),
                ("thumbnail", models.ImageField(upload_to="media")),
            ],
        ),
        migrations.AddField(
            model_name="course",
            name="topics",
            field=models.ManyToManyField(to="web.topic"),
        ),
    ]
