# Generated by Django 4.2.7 on 2023-11-28 11:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0068_topic_course_topics"),
    ]

    operations = [
        migrations.AddField(
            model_name="topic",
            name="auther_image",
            field=models.ImageField(default=1, upload_to="media"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="topic",
            name="authername",
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="topic",
            name="date",
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="topic",
            name="howmany_videos",
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="topic",
            name="video_title",
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
