# Generated by Django 4.2.7 on 2023-11-28 11:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0069_topic_auther_image_topic_authername_topic_date_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="topic",
            name="name",
        ),
    ]
