# Generated by Django 4.2.7 on 2023-11-28 11:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0070_remove_topic_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="course",
            name="topics",
        ),
        migrations.AddField(
            model_name="topic",
            name="name",
            field=models.CharField(
                choices=[
                    ("html", "HTML"),
                    ("css", "CSS"),
                    ("js", "JavaScript"),
                    ("bootstrap", "Bootstrap"),
                    ("react", "React"),
                    ("python", "Python"),
                    ("psql", "PostgreSQL"),
                ],
                default=1,
                max_length=50,
            ),
            preserve_default=False,
        ),
    ]
