# Generated by Django 4.2.7 on 2023-11-28 11:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0071_remove_course_topics_topic_name"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Topic",
        ),
    ]
