# Generated by Django 4.2.7 on 2023-11-28 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0072_delete_topic"),
    ]

    operations = [
        migrations.AddField(
            model_name="playlist",
            name="playlist_head",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="web.playlisthead",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="video",
            name="video_thumb",
            field=models.FileField(default=1, upload_to="media"),
            preserve_default=False,
        ),
    ]
