# Generated by Django 4.2.7 on 2023-11-29 06:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0075_rename_course_playlisthead_course_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="course",
            field=models.CharField(
                choices=[
                    ("html", "html"),
                    ("css", "css"),
                    ("js", "js"),
                    ("bootstrap", "bootstrap"),
                    ("react", "react"),
                    ("python", "python"),
                    ("psql", "psql"),
                ],
                default=1,
                max_length=50,
            ),
            preserve_default=False,
        ),
    ]
