# Generated by Django 4.2.7 on 2023-11-29 06:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0076_course_course"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="course",
            name="course",
        ),
        migrations.AlterField(
            model_name="course",
            name="authername",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
