# Generated by Django 4.2.5 on 2023-10-22 10:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("web_2", "0002_course_1"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="course_1",
            new_name="course",
        ),
    ]
