# Generated by Django 4.2.5 on 2023-10-22 22:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("web_2", "0006_teacher_profile"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="teacher_profile",
            new_name="d_teacher_profile",
        ),
    ]
