# Generated by Django 4.2.5 on 2023-10-22 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_2', '0008_playlist_1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist_1',
            name='video_thumbnail',
            field=models.FileField(upload_to='media'),
        ),
    ]
