# Generated by Django 4.2.5 on 2023-10-23 05:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web_2", "0013_course_2"),
    ]

    operations = [
        migrations.CreateModel(
            name="playlist_2",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("video_thumbnail", models.FileField(upload_to="media")),
                ("video_title", models.CharField(max_length=50)),
            ],
        ),
    ]
