# Generated by Django 4.2.5 on 2023-11-02 05:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web_2", "0020_remove_profile_form_pic_profile_form_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile_form",
            name="image",
            field=models.FileField(upload_to="media"),
        ),
    ]
