# Generated by Django 4.2.5 on 2023-11-07 01:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("web_2", "0024_test_details"),
    ]

    operations = [
        migrations.DeleteModel(
            name="test_details",
        ),
    ]
