# Generated by Django 4.2.7 on 2023-11-10 09:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("web_2", "0025_delete_test_details"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="contact_form",
            new_name="ContactForm",
        ),
        migrations.RenameModel(
            old_name="course_2",
            new_name="Course1",
        ),
        migrations.RenameModel(
            old_name="course_3",
            new_name="Course2",
        ),
        migrations.RenameModel(
            old_name="course_1",
            new_name="Course3",
        ),
        migrations.RenameModel(
            old_name="d_playlist_head",
            new_name="DPlaylistHead",
        ),
        migrations.RenameModel(
            old_name="d_teacher_profile",
            new_name="DTeacherProfile",
        ),
        migrations.RenameModel(
            old_name="d_watch_video_3",
            new_name="DWatchVideo",
        ),
        migrations.RenameModel(
            old_name="d_watch_video",
            new_name="DWatchVideo2",
        ),
        migrations.RenameModel(
            old_name="d_watch_video_2",
            new_name="DWatchVideo3",
        ),
        migrations.RenameModel(
            old_name="playlist_2",
            new_name="Playlist1",
        ),
        migrations.RenameModel(
            old_name="playlist_3",
            new_name="Playlist2",
        ),
        migrations.RenameModel(
            old_name="playlist_1",
            new_name="Playlist3",
        ),
        migrations.RenameModel(
            old_name="profile_form",
            new_name="ProfileForm",
        ),
    ]
