# Generated by Django 4.2.7 on 2023-11-27 07:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("web_2", "0026_rename_contact_form_contactform_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Course2",
        ),
        migrations.DeleteModel(
            name="Course3",
        ),
        migrations.DeleteModel(
            name="DWatchVideo2",
        ),
        migrations.DeleteModel(
            name="DWatchVideo3",
        ),
        migrations.DeleteModel(
            name="Playlist2",
        ),
        migrations.DeleteModel(
            name="Playlist3",
        ),
    ]
