# Generated by Django 4.2.7 on 2023-11-28 06:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web_2", "0027_delete_course2_delete_course3_delete_dwatchvideo2_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dteacherprofile",
            name="insta_url",
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name="dteacherprofile",
            name="linkedin_url",
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name="dteacherprofile",
            name="wp_url",
            field=models.URLField(),
        ),
    ]
